version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  express:
    build:
      context: ./express-app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - app-network

  react:
    build:
      context: ./react-app
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
